repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: python mypy
        always_run: true
        pass_filenames: false
        args: ["python"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        name: ruff
        pass_filenames: false
        always_run: true
        args: ["python", "--fix"]
      - id: ruff-format
        name: ruff
        pass_filenames: false
        always_run: true
        args: ["python"]
