[tool.poetry]
name = "psqlpy-sqlalchemy"
version = "0.1.0"
description = ""
authors = ["chandr-andr (Kiselev Aleksandr) <chandr@chandr.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
psqlpy = "^0.11.1"
sqlalchemy = "2.0.43"
greenlet = "^3.2.4"


# https://github.com/nat-n/poethepoet
[tool.poe]
poetry_command = ""

[tool.poe.tasks.configure]
help = "configure all for local development (CLI commands with poe, pre commit hooks (update on project and install))"
shell = "poetry self add 'poethepoet[poetry_plugin]' && pre-commit autoupdate && pre-commit install"

[tool.poe.tasks.lint]
help = "ruff linter for only changed files"
shell = "ruff check $(git diff --name-only -- '*.py')"
interpreter = ["powershell", "posix"]

[tool.poe.tasks.format]
shell = "ruff format ."
interpreter = ["powershell", "posix"]

[tool.poe.tasks.isort]
help = "sort all files with ruff rules"
control.expr = "sys.platform"

[[tool.poe.tasks.isort.switch]]
case = ["linux", "darwin"]
interpreter = "posix"
shell = "(git --no-pager diff --name-only -- '*.py' && git diff --staged --name-only -- '*.py') | xargs -r ruff check --select I --fix $file"

[[tool.poe.tasks.isort.switch]]
case = "win32"
interpreter = "powershell"
shell = "(git --no-pager diff --name-only -- '*.py' -and git diff --staged --name-only -- '*.py') | ForEach-Object { ruff check --select I --fix $_ $file}"

[tool.poe.tasks.code-check]
help = "run all code checking/formatting tools (format, isort, lint)"
sequence = ["format", "isort", "lint"]

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.11"
mypy = "^1.15.0"
pytest = "^8.4.2"
sqlalchemy = "^2.0.43"
pytest-anyio = "^0.0.0"
pre-commit = "^4.3.0"
poethepoet = {extras = ["poetry-plugin"], version = "^0.37.0"}

[tool.poetry.plugins."sqlalchemy.dialects"]
"postgresql.psqlpy" = "psqlpy_sqlalchemy.dialect:PSQLPyAsyncDialect"
"postgresql+psqlpy" = "psqlpy_sqlalchemy.dialect:PSQLPyAsyncDialect"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
preview = true
extend-select = ["ALL"]
extend-ignore = [
  "D10",
  "D203",
  "D212",
  "TD003",
  "FIX",
  "CPY",
  "ANN",
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",
]

[tool.ruff.lint.extend-per-file-ignores]
"**/tests/*" = [
  "S101",
  "SLF001",
]

[tool.ruff.lint.pylint]
max-args = 5

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.isort]
case-sensitive = true

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_return_any = false
warn_unused_ignores = false
